application: codeigniter-gae-app
service: default
runtime: php55

handlers:
- url: /user_guide/
  static_files: user_guide/index.html
  upload: user_guide/index.html

- url: /user_guide/(.*)
  static_files: user_guide/\1
  upload: user_guide/(.*)

- url: /static/(.*)
  static_files: static/\1
  upload: static/(.*)

- url: /
  script: index.php

- url: /(.+)
  script: index.php
