service: default
runtime: php55

env_variables:
  # Put production environment variables here.
  MYSQL_DSN: mysql:unix_socket=/cloudsql/INSTANCE_CONNECTION_NAME;dbname=DATABASE
  MYSQL_USER: cloudsql_username
  MYSQL_PASSWORD: cloudsql_password
  MYSQL_DB: cloudsql_database_name

handlers:
- url: /user_guide/
  static_files: user_guide/index.html
  upload: user_guide/index.html

- url: /user_guide/(.*)
  static_files: user_guide/\1
  upload: user_guide/(.*)

- url: /static/(.*)
  static_files: static/\1
  upload: static/(.*)

- url: /
  script: index.php

- url: /(.+)
  script: index.php
